name: PR Checks

on:
  pull_request:
    branches:
      - main
      - develop  # Add other branches as needed

jobs:
  test-and-lint:
    name: Run Unit Tests & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust as needed

      - name: Install Dependencies
        run: |
          python -m venv venv_fraud_mlops
          source venv_fraud_mlops/bin/activate
          python -m pip install --upgrade pip
          pip install uv
          pip install poetry
          uv pip install -r pyproject.toml

      - name: Run Unit Tests with pytest
        run: pytest tests/ --disable-warnings --maxfail=5

      - name: Check Code Formatting with Black
        run: black --check .

      - name: Lint Code with Flake8
        run: flake8 .

      - name: Run Security Checks with Bandit
        run: bandit -q -r .
